### ISSUE TITLE
Include ioggstream's proposals into the new draft

### ISSUE THREAD

**Issue by bfabio** [teamdigitale/dati-semantic-guida-ndc-docs#21]
@ioggstream made a few proposals for the docs, we should include them in the new draft both here and in the cookie-cutter repo: https://github.com/teamdigitale/dati-semantic-guida-ndc-docs/pull/15#pullrequestreview-1752392203

**Comment by Clou-dia** [comment]
@AgostinoPurificato could you check if the proposals are in the new guide?

**Comment by AgostinoPurificato** [comment]
@Clou-dia @bfabio
The suggested changes no longer apply to the cookie-cutter repository since with https://github.com/teamdigitale/dati-semantic-cookiecutter/pull/19 we removed files that explained things already described in the new guide, so we replaced some of the files with links to the guide. 

In any case, I will incorporate the suggestions where applicable in the new guide.
